In [26]:
#Using any supervised learning algorithm showcase the working of a simple machine learning 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import  StandardScaler
from sklearn.linear_model import LogisticRegression


df=pd.read_csv(r"C:\Users\Admin\Desktop\Datasets\Heart.csv")
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [29]:
df2=df.drop(columns=['Unnamed: 0','Ca']) # one unwanted column and ca consisting of nan value
df2

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,typical,110,264,0,0,132,0,1.2,2,reversable,Yes
299,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,reversable,Yes
300,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,reversable,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,normal,Yes
302,38,1,nonanginal,138,175,0,0,173,0,0.0,1,normal,No

In [30]:
df2['ChestPain']=df2['ChestPain'].astype('category')
df2['ChestPain']=df2['ChestPain'].cat.codes

df2['Thal']=df2['Thal'].astype('category')
df2['Thal']=df2['Thal'].cat.codes

df2['AHD']=df2['AHD'].astype('category')
df2['AHD']=df2['AHD'].cat.codes

df2

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Thal,AHD
0,63,1,3,145,233,1,2,150,0,2.3,3,0,0
1,67,1,0,160,286,0,2,108,1,1.5,2,1,1
2,67,1,0,120,229,0,2,129,1,2.6,2,2,1
3,37,1,1,130,250,0,0,187,0,3.5,3,1,0
4,41,0,2,130,204,0,2,172,0,1.4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,1,3,110,264,0,0,132,0,1.2,2,2,1
299,68,1,0,144,193,1,0,141,0,3.4,2,2,1
300,57,1,0,130,131,0,0,115,1,1.2,2,2,1
301,57,0,2,130,236,0,2,174,0,0.0,2,1,1
302,38,1,1,138,175,0,0,173,0,0.0,1,1,0

In [31]:
df2.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Thal         0
AHD          0
dtype: int64

In [34]:
x=df2.drop(columns='AHD')
y=df2['AHD']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
scaler=StandardScaler()
x_train_scaler=scaler.fit_transform(x_train)
x_test_scaler=scaler.transform(x_test)
x_train_scaler

array([[ 1.12414392,  0.71713717,  2.14827618, ...,  0.29568949,
         0.64109419, -0.4706162 ],
       [ 0.79633304,  0.71713717, -0.89471636, ...,  0.62648724,
         0.64109419,  1.13858757],
       [ 0.24998157,  0.71713717,  0.11961449, ...,  0.46108836,
        -0.95787015, -0.4706162 ],
       ...,
       [ 0.46852216,  0.71713717, -0.89471636, ..., -0.86210261,
        -0.95787015,  1.13858757],
       [ 0.68706275,  0.71713717, -0.89471636, ...,  0.70918667,
        -0.95787015,  1.13858757],
       [ 0.24998157, -1.39443338, -0.89471636, ..., -0.86210261,
        -0.95787015, -0.4706162 ]])

In [35]:
x_test_scaler

array([[-0.18709961,  0.71713717,  0.11961449, ..., -0.86210261,
        -0.95787015, -0.4706162 ],
       [-0.07782931,  0.71713717, -0.89471636, ..., -0.86210261,
         0.64109419, -0.4706162 ],
       [ 0.14071127,  0.71713717, -0.89471636, ...,  0.13029062,
         0.64109419, -0.4706162 ],
       ...,
       [ 1.01487363,  0.71713717,  0.11961449, ...,  0.62648724,
         0.64109419,  1.13858757],
       [ 0.35925186,  0.71713717, -0.89471636, ..., -0.20050712,
        -0.95787015,  1.13858757],
       [ 0.35925186,  0.71713717,  0.11961449, ..., -0.36590599,
         0.64109419,  1.13858757]])

In [41]:
lg_reg=LogisticRegression().fit(x_train_scaler,y_train)
lg_reg.predict(x_train_scaler)

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0], dtype=int8)

In [44]:
lg_reg.score(x_train_scaler,y_train)

0.8018867924528302

In [46]:
lg_reg.predict(x_test_scaler)

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1], dtype=int8)

In [48]:
lg_reg.score(x_test_scaler,y_test)

0.8021978021978022